sudo: false
language: node_js
node_js:
- 6.10.1
cache:
  directories:
  - node_modules
notifications:
  email: false
install:
- make install
script:
- make test
deploy:
  provider: script
  script: make deploy
  on:
    branch: master
